---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: pre-start
  image: 001575623345.dkr.ecr.eu-west-1.amazonaws.com/drone-tools:1.17.16
  commands:
  - pre-start-scripts
  environment:
    COUNTRY: it

- name: cache-restore
  image: 001575623345.dkr.ecr.eu-west-1.amazonaws.com/drone-tools:1.17.16
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - cache-restore
  environment:
    COUNTRY: it
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  - name: docker
    path: /var/run/docker.sock
  - name: docker-conf
    path: /root/.docker

- name: check-secrets
  image: 001575623345.dkr.ecr.eu-west-1.amazonaws.com/drone-tools:1.17.16
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - check-secrets-grants
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint

- name: build-image
  image: 001575623345.dkr.ecr.eu-west-1.amazonaws.com/drone-tools:1.17.16
  commands:
  - sed -i 's/USER node/USER root/g' ./Dockerfile
  - docker build -t prima/pyxis-components-ci:1 ./
  volumes:
  - name: docker
    path: /var/run/docker.sock
  - name: docker-conf
    path: /root/.docker
  depends_on:
  - cache-restore

- name: dependencies
  image: prima/pyxis-components-ci:1
  commands:
  - yarn
  environment:
    ELM_HOME: /drone/src/.cache/elm
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - pre-start
  - build-image

- name: elm-analyse
  image: prima/pyxis-components-ci:1
  commands:
  - yarn elm-analyse
  environment:
    ELM_HOME: /drone/src/.cache/elm
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - dependencies

- name: elm-review
  image: prima/pyxis-components-ci:1
  commands:
  - yarn elm-review
  environment:
    ELM_HOME: /drone/src/.cache/elm
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - dependencies

- name: test
  image: prima/pyxis-components-ci:1
  commands:
  - yarn elm-test
  environment:
    ELM_HOME: /drone/src/.cache/elm
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - dependencies

- name: cache-save
  image: 001575623345.dkr.ecr.eu-west-1.amazonaws.com/drone-tools:1.17.16
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - cache-save .cache node_modules elm-stuff
  environment:
    COUNTRY: it
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  - name: docker
    path: /var/run/docker.sock
  - name: docker-conf
    path: /root/.docker
  when:
    branch:
    - master
  depends_on:
  - dependencies
  - elm-analyse
  - elm-review
  - test

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: ecs
  host:
    path: /etc/profile.d/ecs-credentials-endpoint
- name: docker-conf
  host:
    path: /home/ec2-user/.docker

trigger:
  event:
  - push

---
kind: pipeline
name: email-failure

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: email-failure
  image: drillster/drone-email
  settings:
    from: noreply@prima.it
    host: email-smtp.eu-west-1.amazonaws.com
  environment:
    PLUGIN_PASSWORD:
      from_secret: email_password
    PLUGIN_USERNAME:
      from_secret: email_username

trigger:
  event:
  - push
  status:
  - failure

depends_on:
- default

---
kind: signature
hmac: 8d7c81c1426130fd17bb438d74e8527a750a9fd51d95992e203bb4e6dafc48f7

...
