---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git-clone
  image: public.ecr.aws/prima/drone-git:1.3-3
  environment:
    PLUGIN_DEPTH: 5

- name: cache-restore
  image: public.ecr.aws/prima/drone-tools:1.21.2
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - cache-restore
  environment:
    BUCKET_NAME: prima-ci-cache
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  - name: docker
    path: /var/run/docker.sock
  depends_on:
  - git-clone

- name: check-secrets
  image: public.ecr.aws/prima/drone-tools:1.21.2
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - check-secrets-grants
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  depends_on:
  - git-clone

- name: check-public-docker-images
  image: public.ecr.aws/prima/drone-tools:1.21.2
  commands:
  - check-public-docker-images
  depends_on:
  - git-clone

- name: build-image
  image: public.ecr.aws/prima/drone-tools:1.21.2
  commands:
  - sed -i 's/USER node/USER root/g' ./Dockerfile
  - docker build -t prima/pyxis-components-ci:${DRONE_COMMIT} ./
  volumes:
  - name: docker
    path: /var/run/docker.sock
  depends_on:
  - cache-restore

- name: dependencies
  image: prima/pyxis-components-ci:${DRONE_COMMIT}
  commands:
  - yarn
  environment:
    ELM_HOME: /drone/src/.cache/elm
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - build-image

- name: elm-analyse
  image: prima/pyxis-components-ci:${DRONE_COMMIT}
  commands:
  - yarn elm-analyse
  environment:
    ELM_HOME: /drone/src/.cache/elm
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - dependencies

- name: elm-review
  image: prima/pyxis-components-ci:${DRONE_COMMIT}
  commands:
  - yarn elm-review
  environment:
    ELM_HOME: /drone/src/.cache/elm
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - dependencies

- name: test
  image: prima/pyxis-components-ci:${DRONE_COMMIT}
  commands:
  - yarn elm-test
  environment:
    ELM_HOME: /drone/src/.cache/elm
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - dependencies

- name: cache-save
  image: public.ecr.aws/prima/drone-tools:1.21.2
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - cache-save .cache node_modules elm-stuff
  environment:
    BUCKET_NAME: prima-ci-cache
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  - name: docker
    path: /var/run/docker.sock
  when:
    branch:
    - master
  depends_on:
  - dependencies
  - elm-analyse
  - elm-review
  - test

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: ecs
  host:
    path: /etc/profile.d/ecs-credentials-endpoint

trigger:
  event:
  - push

---
kind: pipeline
name: email-failure

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: email-failure
  image: public.ecr.aws/prima/drone-email
  settings:
    from: drone@prima.it
    host: email-smtp.eu-west-1.amazonaws.com
  environment:
    PLUGIN_PASSWORD:
      from_secret: email_password
    PLUGIN_USERNAME:
      from_secret: email_username

trigger:
  status:
  - failure
  target:
    exclude:
    - qa-stack
    - qa-it
    - qa

depends_on:
- default

---
kind: signature
hmac: 0d67a4b271f4ebdf97780aa22e3928761deccdb9c909495eb5693ee61e0af60d

...
